---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-volume-provisioner-system-persistent-volume-provisioner
  namespace: local-volume
subjects:
- kind: ServiceAccount
  name: local-volume-provisioner
  namespace: local-volume
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-volume-provisioner-system-node
  namespace: local-volume
subjects:
- kind: ServiceAccount
  name: local-volume-provisioner
  namespace: local-volume
roleRef:
  kind: ClusterRole
  name: local-volume-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
